### ISSUE TITLE
JavaScript Error: Uncaught Exception

### ISSUE THREAD

**Issue by mehreencs87** [auth0-samples/auth0-electron-samples#5]
AUTH-3443
After execute npm install and npm start, click on login with any social or database connection and even on signup, received a popup with this error Cannot set property 'openerId' of undefined.
Both Projects : this Seed and my app results in this issue.
![electron](https://cloud.githubusercontent.com/assets/14890513/19306614/f11ba19e-908f-11e6-8cc9-be106e8bc089.JPG)

**Comment by MaximeFrancoeur** [comment]
look this issue : https://github.com/auth0-samples/auth0-electron-samples/issues/4

**Comment by mehreencs87** [comment]
After execute npm install and npm start, click on login with any social or database connection and even on signup, received a popup with this error Cannot set property 'openerId' of undefined.
