### ISSUE TITLE
After I login a window opens and close very fast and I receive a error.

### ISSUE THREAD

**Issue by MaximeFrancoeur** [auth0-samples/auth0-electron-samples#7]
![error](https://cloud.githubusercontent.com/assets/5606361/19331915/88ccffb8-90b5-11e6-9fcb-2654da611eeb.jpeg)
Error message on login widget : `WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.`

Electron version 1.4.2

Login with mail et password.

**Comment by chenkie** [comment]
Fixed by #8
